language: node_js

node_js:
  - node
  - 8.4.0
  - 9.0.0
  - 10.0.0
  - 11.0.0
  - 12.0.0
  
sudo: false

install:
  - npm install
  
cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm

notifications:
  email: 
    - stitchnig@gmail.com
